/**
 * MC4 SRL
 * Santa Cruz - Bolivia
 * project: back-office-ui
 * date:    18-06-19
 * author:  fmontero
 **/

export enum AlarmType {
  GENERACION_FACTURA_ERROR = 'GENERACION_FACTURA_ERROR',
  ENVIO_FACTURA_ERROR = 'ENVIO_FACTURA_ERROR',
  NOTIFICACION_FACTURA = 'NOTIFICACION_FACTURA',
  VENCIMIENTO_CERTIFICADO = 'VENCIMIENTO_CERTIFICADO',
  CUFD_SINCRONIZACION_ERROR = 'CUFD_SINCRONIZACION_ERROR',
  ERROR_GENERICO = 'ERROR_GENERICO',
}
