/**
 * MC4
 * Santa Cruz - Bolivia
 * project: back-office-ui
 * package:
 * date:    05-02-19
 * author:  fmontero
 * update:  rfernandez
 * date:    22-07-19
 **/

export enum InvoiceType {

  FACTURA_ESTANDAR = 'FACTURA_ESTANDAR',

  FACTURA_COLEGIO = 'FACTURA_COLEGIO',

  FACTURA_ALQUILER = 'FACTURA_ALQUILER',

  FACTURA_COMBUSTIBLE = 'FACTURA_COMBUSTIBLE',

  FACTURA_SERVICIO = 'FACTURA_SERVICIO',

  FACTURA_EMBOTELLADORA = 'FACTURA_EMBOTELLADORA',

  FACTURA_BANCO = 'FACTURA_BANCO',

  FACTURA_HOTEL = 'FACTURA_HOTEL',

  FACTURA_HOSPITAL = 'FACTURA_HOSPITAL',

  FACTURA_JUEGO = 'FACTURA_JUEGO',

  FACTURA_ES00PECTACULO_PUBLICO_INTERNACIONAL = 'FACTURA_ES00PECTACULO_PUBLICO_INTERNACIONAL',

  NOTA_EXPORTACION = 'NOTA_EXPORTACION',

  NOTA_LIBRE_CONSIGNACION = 'NOTA_LIBRE_CONSIGNACION',

  NOTA_ZONA_FRANCA = 'NOTA_ZONA_FRANCA',

  NOTA_ESPECTACULO_PUBLICO_NACIONAL = 'NOTA_ESPECTACULO_PUBLICO_NACIONAL',

  NOTA_SEGURIDAD_ALIMENTARIA = 'NOTA_SEGURIDAD_ALIMENTARIA',

  NOTA_MONEDA_EXTRANJERA = 'NOTA_MONEDA_EXTRANJERA',

  NOTA_DEBITO_CREDITO = 'NOTA_DEBITO_CREDITO',

  NOTA_CONCILIACION = 'NOTA_CONCILIACION',

  BOLETO_AEREO = 'BOLETO_AEREO',

  NOTA_TURISMO_RECEPTIVO = 'NOTA_TURISMO_RECEPTIVO',

  NOTA_TASA_CERO = 'NOTA_TASA_CERO',

  FACTURA_HIDROCARBURO = 'FACTURA_HIDROCARBURO',

  //Adicionados por rfernandez
  FACTURA_COMERCIAL_EXPORTACION= 'FACTURA_COMERCIAL_EXPORTACION',
  FACTURA_FINANCIERA= 'FACTURA_FINANCIERA',
  FACTURA_EDUCATIVO= 'FACTURA_EDUCATIVO'

}
