/**
 * MC4 SRL
 * Santa Cruz - Bolivia
 * project: back-office-ui
 * date:    26-07-19
 * author:  fmontero
 **/

export enum PackageState {
  PAQUETE_GENERADO = 'PAQUETE_GENERADO',
  NUEVO = 'NUEVO',
  ERROR_GENERACION_PAQUETE = 'ERROR_GENERACION_PAQUETE',
  ENVIADO_SIN = 'ENVIADO_SIN',
  ERROR_ENVIO_SIN = 'ERROR_ENVIO_SIN',
  VERIFICADO = 'VERIFICADO',
  ERROR_VERIFICACION_SIN = 'ERROR_VERIFICACION_SIN'
}
