/**
 * Reportate
 * Santa Cruz - Bolivia
 * project: back-office-ui
 * package:
 * date:    05-02-19
 * author:  fmontero
 **/

export enum ParametricType {
  TIPO_PARAMETRICA_LISTA_LEYENDA_FACTURA = 'TIPO_PARAMETRICA_LISTA_LEYENDA_FACTURA',

  TIPO_PARAMETRICA_ACTIVIDADES = 'TIPO_PARAMETRICA_ACTIVIDADES',

  TIPO_PARAMETRICA_LISTA_MENSAJE_SERVICIOS = 'TIPO_PARAMETRICA_LISTA_MENSAJE_SERVICIOS',

  TIPO_PARAMETRICA_LISTA_PRODUCTO_SERVICIOS = 'TIPO_PARAMETRICA_LISTA_PRODUCTO_SERVICIOS',

  TIPO_PARAMETRICA_EVENTOS_SIGNIFICATIVOS = 'TIPO_PARAMETRICA_EVENTOS_SIGNIFICATIVOS',

  TIPO_PARAMETRICA_MOTIVO_ANULACION = 'TIPO_PARAMETRICA_MOTIVO_ANULACION',

  TIPO_PARAMETRICA_PAIS_ORIGEN = 'TIPO_PARAMETRICA_PAIS_ORIGEN',

  TIPO_PARAMETRICA_TIPO_AMBIENTE = 'TIPO_PARAMETRICA_TIPO_AMBIENTE',

  TIPO_PARAMETRICA_TIPO_COMPONENTE = 'TIPO_PARAMETRICA_TIPO_COMPONENTE',

  TIPO_PARAMETRICA_TIPO_DEPARTAMENTO = 'TIPO_PARAMETRICA_TIPO_DEPARTAMENTO',

  TIPO_PARAMETRICA_TIPO_DOCUMENTO_FISCAL = 'TIPO_PARAMETRICA_TIPO_DOCUMENTO_FISCAL',

  TIPO_PARAMETRICA_TIPO_DOCUMENTO_IDENTIDAD = 'TIPO_PARAMETRICA_TIPO_DOCUMENTO_IDENTIDAD',

  TIPO_PARAMETRICA_TIPO_DOCUMENTO_SECTOR = 'TIPO_PARAMETRICA_TIPO_DOCUMENTO_SECTOR',

  TIPO_PARAMETRICA_TIPO_EMISION = 'TIPO_PARAMETRICA_TIPO_EMISION',

  TIPO_PARAMETRICA_TIPO_MODALIDAD = 'TIPO_PARAMETRICA_TIPO_MODALIDAD',

  TIPO_PARAMETRICA_TIPO_MONEDA = 'TIPO_PARAMETRICA_TIPO_MONEDA',

  TIPO_PARAMETRICA_TIPO_PUNTO_VENTA = 'TIPO_PARAMETRICA_TIPO_PUNTO_VENTA',

  TIPO_PARAMETRICA_METODO_PAGO = 'TIPO_PARAMETRICA_METODO_PAGO',

  TIPO_PARAMETRICA_UNIDAD_MEDIDA = 'TIPO_PARAMETRICA_UNIDAD_MEDIDA',


}
