export const AUTH_SET_USER             = "AUTH_SET_USER";
export const AUTH_LOGOUT               = "AUTH_LOGOUT";
export const FAMILY_SET_DATA           = "FAMILY_SET_DATA";
export const FAMILY_ADD_MEMBER         = "FAMILY_ADD_MEMBER";
export const FAMILY_UPDATE_MEMBER      = "FAMILY_UPDATE_MEMBER";
export const FAMILY_SET_FIRST_CONTROL  = "FAMILY_SET_FIRST_CONTROL";
export const FAMILY_SET_UPDATE_MEMBER  = "FAMILY_SET_UPDATE_MEMBER";
export const FAQ_SET_DATA              = "FAQ_SET_DATA";
export const APP_CONFIG_SET_MESSAGE    = "APP_CONFIG_SET_MESSAGE";
export const APP_CONFIG_SET_DEPARTMENT = "APP_CONFIG_SET_DEPARTMENT";
export const APP_CONFIG_SET_BASE_DATA  = "APP_CONFIG_SET_BASE_DATA";

export const COUNTRY_SET_ALL_LIST      = 'COUNTRY_SET_ALL_LIST';
export const COUNTRY_SET_SELECTED      = 'COUNTRY_SET_SELECTED';
export const COUNTRY_SET_FILTERED_LIST = 'COUNTRY_SET_FILTERED_LIST';
