export const AUTH_SET_USER     = "AUTH_SET_USER";
export const FAMILY_SET_FAMILY = "FAMILY_SET_FAMILY";
export const FAQ_SET_DATA      = "FAQ_SET_DATA";

export const COUNTRY_SET_ALL_LIST      = 'COUNTRY_SET_ALL_LIST';
export const COUNTRY_SET_SELECTED      = 'COUNTRY_SET_SELECTED';
export const COUNTRY_SET_FILTERED_LIST = 'COUNTRY_SET_FILTERED_LIST';
